config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [ :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # @restaurant = Restaurant.find(params[:id])
     @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
    @review = Review.new

  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path

  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # def index
  #   @reviews = Review.all
  # end

  # def new

  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #   @review = Review.new
  # end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant.id)
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1> List of Restaurants</h1>
<% @restaurants.each do |restaurant| %>
<ul>
  <li>

    <%= restaurant.name.capitalize %> : <%= restaurant.address %>
      <%= link_to "details" , restaurant_path(restaurant.id)  %>
  </li>
</ul>
<% end %>

<%= link_to "Add a restaurant", new_restaurant_path  %>

app/views/restaurants/new.html.erb
<h1> Add a restaurant </h1>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name, label: 'Restaurant name please', error: 'A restaurant needs a name ...' , placeholder: "Ex: Le Jules Vernes"  %>
    <%= f.input :address, placeholder: "Ex: 16 avenue des champs Elysée, 75008 Paris" %>
    <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], prompt: "Select your category" %>
    <%= f.input :phone_number, as: :integer %>
    <%=  f.button :submit, :class => "btn-primary" %>
  <% end %>





<!--
  t.string "name"
    t.string "address"
    t.integer "phone_number"
    t.string "category"
 -->

app/views/restaurants/show.html.erb
<h1>Details</h1>
<h3><%= @restaurant.name %></h3>


<% @restaurant.reviews.each  do |review| %>
  <ul>
    <li> <%= review.content %> <%= review.rating %> </li>
  </ul>
<% end %>


<h3> Add a review</h3>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content , placeholder: "Ex: Excellente resto, every things was delicious"  %>
  <%= f.input :rating, collection: [1,2,3,4,5], prompt: "Rate this restaurant" %>

  <%=  f.button :submit, :class => "btn-primary" %>
<% end %>


<%= link_to "back",restaurants_path  %>